### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by lepa22** [Mukundan314/vscode-python-docs#1]
Hi! Are there any plans for adding docs for other python libraries, like matplotlib, pandas, sklearn, etc?

**Comment by Mukundan314** [comment]
This is just a fork of https://github.com/masonicboom/vscode-web-browser. I just hardcoded it to open the python docs so it should be easy to add any website that supports iframes.

**Comment by Mukundan314** [comment]
I see no point in this extension.
